In [1]:

pip install beautifulsoup4

Requirement already satisfied: beautifulsoup4 in c:\new folder\lib\site-packages (4.13.5)
Requirement already satisfied: soupsieve>1.2 in c:\new folder\lib\site-packages (from beautifulsoup4) (2.5)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\new folder\lib\site-packages (from beautifulsoup4) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import yfinance as yf
import requests
from bs4 import BeautifulSoup
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [3]:
tesla = yf.Ticker("TSLA")

tesla_data = tesla.history(period="max")

tesla_data.reset_index(inplace=True)

tesla_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2010-06-29 00:00:00-04:00,1.266667,1.666667,1.169333,1.592667,281494500,0.0,0.0
1,2010-06-30 00:00:00-04:00,1.719333,2.028000,1.553333,1.588667,257806500,0.0,0.0
2,2010-07-01 00:00:00-04:00,1.666667,1.728000,1.351333,1.464000,123282000,0.0,0.0
3,2010-07-02 00:00:00-04:00,1.533333,1.540000,1.247333,1.280000,77097000,0.0,0.0
4,2010-07-06 00:00:00-04:00,1.333333,1.333333,1.055333,1.074000,103003500,0.0,0.0

In [4]:
tesla_data.shape
tesla_data.tail()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
4011,2026-06-10 00:00:00-04:00,391.540009,397.089996,380.149994,381.589996,49695600,0.0,0.0
4012,2026-06-11 00:00:00-04:00,388.279999,399.540009,380.660004,399.149994,45324300,0.0,0.0
4013,2026-06-12 00:00:00-04:00,399.489990,406.679993,386.760010,406.429993,63514500,0.0,0.0
4014,2026-06-15 00:00:00-04:00,412.369995,416.000000,407.100006,411.149994,45620500,0.0,0.0
4015,2026-06-16 00:00:00-04:00,404.109985,412.420013,400.540009,405.750000,34770144,0.0,0.0

In [5]:
amazon = yf.Ticker("AMZN")

amazon_data = amazon.history(period="max")

amazon_data.reset_index(inplace=True)

amazon_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,1997-05-15 00:00:00-04:00,0.121875,0.125000,0.096354,0.097917,1443120000,0.0,0.0
1,1997-05-16 00:00:00-04:00,0.098438,0.098958,0.085417,0.086458,294000000,0.0,0.0
2,1997-05-19 00:00:00-04:00,0.088021,0.088542,0.081250,0.085417,122136000,0.0,0.0
3,1997-05-20 00:00:00-04:00,0.086458,0.087500,0.081771,0.081771,109344000,0.0,0.0
4,1997-05-21 00:00:00-04:00,0.081771,0.082292,0.068750,0.071354,377064000,0.0,0.0

In [6]:
amd = yf.Ticker("AMD")

amd_data = amd.history(period="max")

amd_data.reset_index(inplace=True)

amd_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,1980-03-17 00:00:00-05:00,3.125000,3.302083,3.125000,3.145833,219600,0.0,0.0
1,1980-03-18 00:00:00-05:00,3.125000,3.125000,2.937500,3.031250,727200,0.0,0.0
2,1980-03-19 00:00:00-05:00,3.031250,3.083333,3.020833,3.041667,295200,0.0,0.0
3,1980-03-20 00:00:00-05:00,3.041667,3.062500,3.010417,3.010417,159600,0.0,0.0
4,1980-03-21 00:00:00-05:00,3.010417,3.020833,2.906250,2.916667,130800,0.0,0.0

In [7]:
import requests
from bs4 import BeautifulSoup

url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm"

html_data = requests.get(url).text

soup = BeautifulSoup(html_data, "html.parser")

In [8]:
print(url)

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/revenue.htm

In [9]:
print(soup.title)

<title>Tesla Revenue 2010-2022 | TSLA | MacroTrends</title>

In [10]:
tables = soup.find_all("table")
print(len(tables))

6

In [11]:
import pandas as pd

tesla_revenue = pd.DataFrame(columns=["Date", "Revenue"])

In [12]:
table = tables[0]

for row in table.find_all("tr"):
    cols = row.find_all("td")

    if len(cols) != 0:
        date = cols[0].text
        revenue = cols[1].text

        tesla_revenue = pd.concat([
            tesla_revenue,
            pd.DataFrame({
                "Date": [date],
                "Revenue": [revenue]
            })
        ], ignore_index=True)

In [13]:
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace(",", "")
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace("$", "", regex=False)

tesla_revenue.dropna(inplace=True)
tesla_revenue = tesla_revenue[tesla_revenue["Revenue"] != ""]

In [14]:
tesla_revenue.tail()

    Date Revenue
8   2013    2013
9   2012     413
10  2011     204
11  2010     117
12  2009     112

In [15]:
print(len(html_data))

64779

In [16]:
tables = soup.find_all("table")
print(len(tables))

6

In [17]:
for i, table in enumerate(tables):
    print(i)
    print(table.text[:200])
    print("-"*50)

0



Tesla Annual Revenue(Millions of US $)




2021
$53,823


2020
$31,536


2019
$24,578


2018
$21,461


2017
$11,759


2016
$7,000


2015
$4,046


2014
$3,198


2013
$2,013


2012
$413


2011
$204


--------------------------------------------------
1



Tesla Quarterly Revenue(Millions of US $)




2022-09-30
$21,454


2022-06-30
$16,934


2022-03-31
$18,756


2021-12-31
$17,719


2021-09-30
$13,757


2021-06-30
$11,958


2021-03-31
$10,389


2020
--------------------------------------------------
2



Sector
Industry
Market Cap
Revenue




Auto/Tires/Trucks
Auto Manufacturers - Domestic
$549.575B
$53.823B



Tesla is the market leader in battery-powered electric car sales in the United States, w
--------------------------------------------------
3



Stock Name
Country
Market Cap
PE Ratio




General Motors (GM)
United States
$53.930B
5.56


Ford Motor (F)
United States
$52.668B
8.09


Harley-Davidson (HOG)
United States
$6.762B
9.56


Polaris
--------------------------------------------------
4



Link Preview
HTML Code (Click to Copy)




Tesla Revenue 2010-2022 | TSLA



Macrotrends



Source




--------------------------------------------------
5



Link Preview
HTML Code (Click to Copy)




Tesla Revenue 2010-2022 | TSLA



Macrotrends



Source




--------------------------------------------------

In [18]:
import pandas as pd

tesla_revenue = pd.DataFrame(columns=["Date","Revenue"])

for row in tables[1].find_all("tr"):
    
    cols = row.find_all("td")
    
    if len(cols) != 0:
        
        date = cols[0].text
        revenue = cols[1].text
        
        tesla_revenue = pd.concat([
            tesla_revenue,
            pd.DataFrame({
                "Date":[date],
                "Revenue":[revenue]
            })
        ], ignore_index=True)

In [19]:
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace(",", "")
tesla_revenue["Revenue"] = tesla_revenue["Revenue"].str.replace("$", "", regex=False)

tesla_revenue = tesla_revenue[tesla_revenue["Revenue"] != ""]
tesla_revenue.dropna(inplace=True)

In [20]:
tesla_revenue.head()

         Date Revenue
0  2022-09-30   21454
1  2022-06-30   16934
2  2022-03-31   18756
3  2021-12-31   17719
4  2021-09-30   13757

In [21]:
tesla_revenue.tail()

          Date Revenue
48  2010-09-30      31
49  2010-06-30      28
50  2010-03-31      21
52  2009-09-30      46
53  2009-06-30      27

In [22]:
import plotly.graph_objects as go
from plotly.subplots import make_subplots

def make_graph(stock_data, revenue_data, stock):

    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        subplot_titles=("Historical Share Price",
                         "Historical Revenue")
    )

    fig.add_trace(
        go.Scatter(
            x=stock_data["Date"],
            y=stock_data["Close"],
            name="Stock Price"
        ),
        row=1, col=1
    )

    revenue_data["Revenue"] = revenue_data["Revenue"].astype("float")

    fig.add_trace(
        go.Scatter(
            x=revenue_data["Date"],
            y=revenue_data["Revenue"],
            name="Revenue"
        ),
        row=2, col=1
    )

    fig.update_layout(
        title=stock,
        height=800,
        showlegend=False
    )

    fig.show()

In [23]:
make_graph(tesla_data, tesla_revenue, "Tesla")

In [24]:
import yfinance as yf

gme = yf.Ticker("GME")

gme_data = gme.history(period="max")

gme_data.reset_index(inplace=True)

gme_data.head()

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,2002-02-13 00:00:00-05:00,1.620128,1.693350,1.603296,1.691666,76216000,0.0,0.0
1,2002-02-14 00:00:00-05:00,1.712707,1.716074,1.670626,1.683251,11021600,0.0,0.0
2,2002-02-15 00:00:00-05:00,1.683251,1.687459,1.658002,1.674834,8389600,0.0,0.0
3,2002-02-19 00:00:00-05:00,1.666418,1.666418,1.578047,1.607504,7410400,0.0,0.0
4,2002-02-20 00:00:00-05:00,1.615921,1.662210,1.603296,1.662210,6892800,0.0,0.0

In [25]:
import requests
from bs4 import BeautifulSoup

url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/gamestop_revenue.htm"

html_data = requests.get(url).text

soup = BeautifulSoup(html_data, "html.parser")

C:\Users\Prakash\AppData\Local\Temp\ipykernel_19464\1354064889.py:8: XMLParsedAsHTMLWarning:

It looks like you're using an HTML parser to parse an XML document.

Assuming this really is an XML document, what you're doing might work, but you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the Python package 'lxml' installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.

If you want or need to use an HTML parser on this document, you can make this warning go away by filtering it. To do that, run this code before calling the BeautifulSoup constructor:

    from bs4 import XMLParsedAsHTMLWarning
    import warnings

    warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)

In [26]:
print(len(html_data))

359

In [27]:
print(soup.title)

None

In [28]:
tables = soup.find_all("table")
print(len(tables))

0

In [29]:
print(url)

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/gamestop_revenue.htm

In [30]:
response = requests.get(url)

print(response.status_code)
print(response.text[:500])

404
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/cf-courses-data/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/gamestop_revenue.htm</Resource><RequestId>52dbc571-b642-4990-bfd5-0c51364fd705</RequestId><httpStatusCode>404</httpStatusCode></Error>

In [31]:
import requests

for u in [
    "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/gamestop_revenue.htm",
    "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/gme_revenue.htm"
]:
    r = requests.get(u)
    print(u)
    print(r.status_code)

https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/gamestop_revenue.htm
404
https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-PY0220EN-SkillsNetwork/labs/project/gme_revenue.htm
404

In [32]:
response = requests.get(url)

print(response.status_code)
print(len(response.text))

404
359

In [33]:
import pandas as pd

try:
    tables = pd.read_html(
        "https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue"
    )
except Exception as e:
    print(type(e))
    print(e)

<class 'urllib.error.HTTPError'>
HTTP Error 403: Forbidden

In [34]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

url = "https://www.macrotrends.net/stocks/charts/GME/gamestop/revenue"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

print(response.status_code)
print(len(response.text))

200
78661

In [35]:
len(response.text)

78661

In [36]:
html = "<html><body>Hello</body></html>"
print(len(html))

31

In [37]:
import pandas as pd

tables = pd.read_html(response.text)

print(len(tables))

4

C:\Users\Prakash\AppData\Local\Temp\ipykernel_19464\2284572935.py:3: FutureWarning:

Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.

In [38]:
for i, table in enumerate(tables):
    print("TABLE:", i)
    print(table.head())
    print("-"*80)

TABLE: 0
   GameStop Annual Revenue (Millions of US $)  \
0                                        2026
1                                        2025
2                                        2024
3                                        2023
4                                        2022

  GameStop Annual Revenue (Millions of US $).1
0                                       $3,630
1                                       $3,823
2                                       $5,273
3                                       $5,927
4                                       $6,011
--------------------------------------------------------------------------------
TABLE: 1
  GameStop Quarterly Revenue (Millions of US $)  \
0                                    2026-04-30
1                                    2026-01-31
2                                    2025-10-31
3                                    2025-07-31
4                                    2025-04-30

  GameStop Quarterly Revenue (Millions of US $).1
0                                            $835
1                                          $1,104
2                                            $821
3                                            $972
4                                            $732
--------------------------------------------------------------------------------
TABLE: 2
                                              Sector  \
0                             Consumer Discretionary
1  GameStop Corp. offers the best selection of ne...

                                            Industry  \
0                                             Gaming
1  GameStop Corp. offers the best selection of ne...

                                          Market Cap  \
0                                           $10.411B
1  GameStop Corp. offers the best selection of ne...

                                             Revenue
0                                            $3.630B
1  GameStop Corp. offers the best selection of ne...
--------------------------------------------------------------------------------
TABLE: 3
                             Stock Name        Country Market Cap  PE Ratio
0                      Nintendo (NTDOY)          Japan   $66.938B     25.00
1                  Electronic Arts (EA)  United States   $50.736B     35.57
2                         Roblox (RBLX)  United States   $36.780B      0.00
3  Take-Two Interactive Software (TTWO)  United States   $36.493B     65.04
4                 Las Vegas Sands (LVS)  United States   $35.470B     17.76
--------------------------------------------------------------------------------

In [39]:
for i in range(len(tables)):
    print(i)
    print(tables[i].columns)
    print()

0
Index(['GameStop Annual Revenue (Millions of US $)', 'GameStop Annual Revenue (Millions of US $).1'], dtype='object')

1
Index(['GameStop Quarterly Revenue (Millions of US $)', 'GameStop Quarterly Revenue (Millions of US $).1'], dtype='object')

2
Index(['Sector', 'Industry', 'Market Cap', 'Revenue'], dtype='object')

3
Index(['Stock Name', 'Country', 'Market Cap', 'PE Ratio'], dtype='object')

In [40]:
gme_revenue = tables[1]

In [41]:
gme_revenue = tables[1]

gme_revenue.columns = ["Date", "Revenue"]

gme_revenue.head()

         Date Revenue
0  2026-04-30    $835
1  2026-01-31  $1,104
2  2025-10-31    $821
3  2025-07-31    $972
4  2025-04-30    $732

In [42]:
gme_revenue["Revenue"] = gme_revenue["Revenue"].astype(str)

gme_revenue["Revenue"] = gme_revenue["Revenue"].str.replace(",", "")
gme_revenue["Revenue"] = gme_revenue["Revenue"].str.replace("$", "", regex=False)

gme_revenue = gme_revenue[gme_revenue["Revenue"] != ""]
gme_revenue.dropna(inplace=True)

In [43]:
gme_revenue.head()

         Date Revenue
0  2026-04-30     835
1  2026-01-31    1104
2  2025-10-31     821
3  2025-07-31     972
4  2025-04-30     732

In [44]:
gme_revenue.tail()

          Date Revenue
55  2012-07-31    1550
56  2012-04-30    2002
57  2012-01-31    3579
58  2011-10-31    1947
59  2011-07-31    1744

In [45]:
make_graph(gme_data, gme_revenue, "GameStop")